version: '3.4'

services:
  budget:
    image: threax.budget
    container_name: budget
    build:
      context: .
      dockerfile: Budget/Dockerfile
    networks:
      - appnet
    volumes:
      - type: bind
        source: ../TrustedRoots
        target: /usr/local/share/ca-certificates
      - type: bind
        source: ../DevData/budget
        target: /appdata

networks:
  appnet:
    external: true