version: '3.4'

services:
  budget:
    image: threax.budget
    build:
      context: Budget
      dockerfile: Dockerfile
    networks:
      - appnet
    volumes:
      - type: bind
        source: ../TrustedRoots
        target: /usr/local/share/ca-certificates
      - type: bind
        source: ../DevData/budget
        target: /appdata
    labels:
      - "threax.nginx.host=budget.dev.threax.com"

networks:
  appnet:
    external: true